@startuml

'Atores
skinparam actorStyle awesome
actor "Administrador" as Admin
actor "Funcionário" as Func

'Verbos
rectangle "Sistema de Controle de Serviços" {
  
  usecase "Gerenciar Entidades" as RF1
  usecase "Alocar Recursos com Serviços" as RF3
  usecase "Controlar Acesso" as RF5
  usecase "Enviar Feedback" as RF6
  usecase "Consultar Agenda" as RF7
  usecase "Gerenciar Funcionário" as RF8
  usecase "Gerenciar Equipamento" as RF9


}

Admin --> RF1
Admin --> RF3
Admin --> RF5

Func --> RF6
Func --> RF7

RF1 --> RF8
RF1 --> RF9

RF3 ..> RF8 : <<include>>
RF3 ..> RF9 : <<include>>
@enduml